# Generated by Django 4.2.8 on 2023-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=155)),
                ('price', models.CharField(max_length=255)),
                ('countries', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('data_access', models.CharField(max_length=255)),
                ('downloads', models.CharField(max_length=255)),
                ('searches', models.CharField(max_length=255)),
                ('workspace', models.CharField(max_length=255)),
                ('records_ws', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
