# Generated by Django 4.2.8 on 2023-12-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subscription_plans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plans',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
